// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDljwK7ChRfMV0Z6_ikkgkLsELFtfUcHwQ',
    appId: '1:265189494364:web:b048ecba679d24fc426099',
    messagingSenderId: '265189494364',
    projectId: 'lingua-notes-f0549',
    authDomain: 'lingua-notes-f0549.firebaseapp.com',
    storageBucket: 'lingua-notes-f0549.appspot.com',
    measurementId: 'G-KTT9VS98KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFFLbCg5FyRPHi2Vfj4hdl21ZypqkHM8',
    appId: '1:265189494364:android:ff41e0b8c00eafe1426099',
    messagingSenderId: '265189494364',
    projectId: 'lingua-notes-f0549',
    storageBucket: 'lingua-notes-f0549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1VZxKOspcIWmnbXsKZZTgj2ymSxKuFtk',
    appId: '1:265189494364:ios:775717f8b1528024426099',
    messagingSenderId: '265189494364',
    projectId: 'lingua-notes-f0549',
    storageBucket: 'lingua-notes-f0549.appspot.com',
    iosBundleId: 'com.example.linguaNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1VZxKOspcIWmnbXsKZZTgj2ymSxKuFtk',
    appId: '1:265189494364:ios:16eae575422345e0426099',
    messagingSenderId: '265189494364',
    projectId: 'lingua-notes-f0549',
    storageBucket: 'lingua-notes-f0549.appspot.com',
    iosBundleId: 'com.example.linguaNotes.RunnerTests',
  );
}
